# Generated by Django 5.2.6 on 2025-10-27 16:46

import django_mongodb_backend.fields
import platform_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequirement',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('table_kind', models.CharField(max_length=10)),
                ('table_name', models.CharField(max_length=20)),
                ('table_columns', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=20))),
                ('time_begin', models.IntegerField(default=0)),
                ('time_end', models.IntegerField(default=0)),
                ('time_unit', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastModule',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('mission_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('module_hash', models.CharField(max_length=64, unique=True)),
                ('alive', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_alive_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('execute_cron_list', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=50))),
                ('execute_shift_time', models.IntegerField(default=0)),
                ('execute_shift_unit', models.CharField(max_length=10)),
                ('next_execution_time', models.DateTimeField(blank=True, null=True)),
                ('last_execution_time', models.DateTimeField(blank=True, null=True)),
                ('input_data', django_mongodb_backend.fields.EmbeddedModelArrayField(embedded_model=platform_app.models.DataRequirement)),
                ('output_data', django_mongodb_backend.fields.EmbeddedModelArrayField(embedded_model=platform_app.models.DataRequirement)),
            ],
            options={
                'db_table': 'forecast_module',
                'indexes': [models.Index(fields=['module_hash'], name='idx_module_hash'), models.Index(fields=['name'], name='idx_name'), models.Index(fields=['alive'], name='idx_alive')],
            },
        ),
    ]
