# Generated by Django 5.2.6 on 2025-11-09 14:45

import django_mongodb_backend.fields
import platform_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('workflow_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('execute_cron_list', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=50))),
                ('execute_shift_time', models.IntegerField(default=0)),
                ('execute_shift_unit', models.CharField(max_length=10)),
                ('execute_modules', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkModule',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('module_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('module_hash', models.CharField(max_length=64, unique=True)),
                ('alive', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_alive_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_execution_time', models.DateTimeField(blank=True, null=True)),
                ('input_data', django_mongodb_backend.fields.EmbeddedModelArrayField(embedded_model=platform_app.models.DataRequirement)),
                ('output_data', django_mongodb_backend.fields.EmbeddedModelArrayField(embedded_model=platform_app.models.DataRequirement)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.DeleteModel(
            name='ForecastModule',
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['name'], name='idx_workflow_name'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['workflow_id'], name='idx_workflow_id'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['enable'], name='idx_workflow_enable'),
        ),
        migrations.AddIndex(
            model_name='workmodule',
            index=models.Index(fields=['module_hash'], name='idx_module_hash'),
        ),
        migrations.AddIndex(
            model_name='workmodule',
            index=models.Index(fields=['name'], name='idx_name'),
        ),
        migrations.AddIndex(
            model_name='workmodule',
            index=models.Index(fields=['alive'], name='idx_alive'),
        ),
        migrations.AddIndex(
            model_name='workmodule',
            index=models.Index(fields=['module_id'], name='idx_module_id'),
        ),
    ]
